# Generated by Django 6.0.2 on 2026-02-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0003_alter_subscription_journalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('newsletter', 'Newsletter')], default='article', max_length=20),
        ),
    ]
