# Generated by Django 6.0.2 on 2026-02-13 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_article_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
