# Generated by Django 6.0.2 on 2026-02-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0005_article_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
