# Generated by Django 6.0.2 on 2026-02-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0006_alter_article_published_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'journalist'), ('user', 'publisher')},
        ),
    ]
